import Link from "next/link"

export default function PricingPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white font-mono">
      <header className="border-b border-[#222] bg-[#0D0D0D] sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-6 h-6 bg-[#FF6600] flex items-center justify-center"><span className="text-xs font-bold">TD</span></div>
            <span className="font-bold tracking-[0.15em]">TRADEDADDY</span>
          </Link>
          <Link href="/" className="text-[#FF6600] hover:text-white text-sm">← BACK</Link>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-12 space-y-12">
        <section>
          <h1 className="text-4xl font-bold text-[#FF6600] mb-6">SUBSCRIPTION PLANS</h1>
          <p className="text-[#999] text-sm mb-8">Choose your trading tier. All plans include a 14-day free trial with no credit card required.</p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {[
              {
                name: "SNIPER",
                price: "R199",
                features: ["300 Credits/month", "Basic trading signals", "Limited market data", "Basic AI access", "Trade journal", "Calculator tools"],
              },
              {
                name: "EXECUTION",
                price: "R399",
                highlight: true,
                features: ["1,200 Credits/month", "Advanced signals", "Full market data", "Advanced AI analysis", "Trade journal", "All calculators", "Daily market intelligence"],
              },
              {
                name: "DOMINANCE",
                price: "R499",
                features: ["4,000 Credits/month", "Priority signals", "Priority market data", "Priority AI support", "Full trade journal", "All calculators", "VIP community access"],
              },
            ].map((plan, i) => (
              <div key={i} className={`border ${plan.highlight ? "border-[#FF6600]" : "border-[#1A1A1A]"} bg-[#0D0D0D] p-6`}>
                <h3 className="text-lg font-bold mb-2">{plan.name}</h3>
                <div className="flex items-baseline gap-1 mb-6">
                  <span className={`text-3xl font-bold ${plan.highlight ? "text-[#FF6600]" : "text-white"}`}>{plan.price}</span>
                  <span className="text-[#555]">/mo</span>
                </div>
                <ul className="space-y-2 mb-6">
                  {plan.features.map((f, j) => (
                    <li key={j} className="flex items-center gap-2 text-xs text-[#888]">
                      <span className="text-[#FF6600]">▶</span> {f}
                    </li>
                  ))}
                </ul>
                <Link href="/auth/sign-up" className={`block text-center text-xs font-bold py-2.5 tracking-widest ${plan.highlight ? "bg-[#FF6600] text-white hover:bg-[#FF7722]" : "border border-[#333] text-[#888] hover:border-[#555]"} transition-colors`}>
                  GET STARTED
                </Link>
              </div>
            ))}
          </div>

          <div className="border border-[#1A1A1A] bg-[#0D0D0D] p-4 text-center">
            <p className="text-[11px] text-[#555]">14-day free trial • No credit card required • Cancel anytime</p>
          </div>
        </section>

        <section className="border-t border-[#1A1A1A] pt-8">
          <h2 className="text-2xl font-bold text-[#FF6600] mb-4">WHAT YOU GET</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="border border-[#1A1A1A] bg-[#0D0D0D] p-4">
              <h4 className="font-bold text-white mb-2">CREDITS</h4>
              <p className="text-xs text-[#888]">Monthly credits used for API calls, signals, and AI requests. Unused credits roll over to next month.</p>
            </div>
            <div className="border border-[#1A1A1A] bg-[#0D0D0D] p-4">
              <h4 className="font-bold text-white mb-2">SIGNALS</h4>
              <p className="text-xs text-[#888]">Trading signals generated by AI analysis. Entry points, take profit, and stop loss included.</p>
            </div>
            <div className="border border-[#1A1A1A] bg-[#0D0D0D] p-4">
              <h4 className="font-bold text-white mb-2">MARKET DATA</h4>
              <p className="text-xs text-[#888]">Live prices for forex, commodities, crypto, and indices. Updated every 15-30 seconds.</p>
            </div>
            <div className="border border-[#1A1A1A] bg-[#0D0D0D] p-4">
              <h4 className="font-bold text-white mb-2">TOOLS & ACADEMY</h4>
              <p className="text-xs text-[#888]">All trading calculators and academy lessons included in every plan.</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
