import { LegalLayout, Section, Para } from "@/components/marketing/LegalLayout"

export const metadata = {
  title: "Signal Disclaimer — TradeDaddy",
}

export default function DisclaimerPage() {
  return (
    <LegalLayout title="SIGNAL DISCLAIMER" activeTab="/legal/disclaimer">
      <Section title="1. NATURE OF SIGNALS">
        <Para>
          Trade signals published on TradeDaddy Terminal are generated by an AI-powered neural
          network and reviewed by senior analysts. They represent a directional view based on
          technical analysis, price action, macro context, and sentiment data at the time of
          generation. Signals are not personalised recommendations and do not take into account
          your individual financial circumstances, risk tolerance, or investment objectives.
        </Para>
      </Section>

      <Section title="2. NOT FINANCIAL ADVICE">
        <Para>
          TradeDaddy signals do NOT constitute financial advice, investment recommendations,
          or solicitations to trade as defined under the Financial Advisory and Intermediary
          Services Act (FAIS) of South Africa. TradeDaddy (Pty) Ltd does not hold an FSP licence.
          Signals are provided for educational and informational purposes only.
        </Para>
      </Section>

      <Section title="3. SIGNAL ACCURACY">
        <Para>
          No signal service — AI-powered or otherwise — achieves 100% accuracy. Markets are
          influenced by events that cannot be predicted or modelled: central bank decisions,
          geopolitical shocks, liquidity changes, and black swan events. A signal with a high
          confidence score can and does result in a loss. Always place your own stop-loss and
          never enter a trade without a defined risk management plan.
        </Para>
      </Section>

      <Section title="4. PAST PERFORMANCE">
        <Para>
          Historical signal performance data published in the terminal is provided for transparency.
          Past performance of signals — including win rates, average risk-to-reward ratios,
          and monthly returns — is not indicative of future performance. You should not base
          trading decisions solely on historical signal results.
        </Para>
      </Section>

      <Section title="5. EXECUTION RISK">
        <Para>
          Signals specify an entry zone, stop-loss, and take-profit levels. Your actual execution
          price may differ from the signal entry zone due to spreads, slippage, gaps, and
          broker-specific conditions. TradeDaddy is not responsible for differences between
          signal prices and actual execution prices at your broker.
        </Para>
      </Section>

      <Section title="6. LEVERAGE WARNING">
        <Para>
          All assets covered by TradeDaddy signals (Forex, Gold, Indices) are commonly traded
          with leverage. Leveraged trading significantly increases both potential gains and
          potential losses. The signal entry, SL, and TP levels are provided as reference points
          — they do not account for your specific leverage ratio, account size, or broker margin
          requirements. Always calculate your position size independently using the calculators
          provided in the terminal.
        </Para>
      </Section>

      <Section title="7. SIGNAL DELAY">
        <Para>
          Signals are published in real-time inside the terminal. Notification delivery (email
          or push) may be subject to delays. Market prices can move significantly in a short
          period. TradeDaddy accepts no responsibility for losses arising from delayed receipt
          or late execution of a signal.
        </Para>
      </Section>

      <Section title="8. YOUR RESPONSIBILITY">
        <Para>
          By using signals provided on TradeDaddy Terminal, you acknowledge that: (a) you have
          read and understood this disclaimer; (b) you accept full responsibility for all trading
          decisions made using these signals; (c) you understand that signals do not guarantee
          profitable outcomes; (d) you will implement appropriate risk management on every trade.
        </Para>
      </Section>
    </LegalLayout>
  )
}
